### ISSUE TITLE
Better validator error messages?

### ISSUE THREAD

**Issue by brendanlong** [mjambon/atd#33]
I was trying to use atdgen to validate fields in a record, similar to the example in the docs:

```
type t =
  { id : string
  ; start_date : date
  ; ?end_date : date option }
  <ocaml valid="Requisition_util.validate_requisition">
```

```
(* requisition_util.ml *)
let validate_requisition { Requisition_t.start_date ; end_date } =
  match end_date with
  | None -> true
  | Some end_date -> Date.(end_date >= start_date)
```

The problem is that the error message is just:

> Validation error; path = &lt;root>

I looked at the code in atdgen/src/validate.ml, and it doesn't seem like there's any way to set `msg`. Is there some way to make the message more useful? I'd really like to return something like "end_date must be >= to start_date".

**Comment by mjambon** [comment]
What you can do is use `validator=` instead of `valid=`. This lets you specify an error message as part of the return value of the validator. The type of your validator function should be `Ag_util.Validation.path -> <your type> -> Ag_util.Validation.error option`. `Ag_util.Validation` provides functions to somewhat help create these validators, but it's cumbersome and it's not documented as it should (see https://github.com/mjambon/atdgen/blob/master/src/ag_util.mli).

**Comment by mjambon** [comment]
Perhaps we could improve the situation by letting the user raise an exception from their validator, and the generated code would catch it and use it as an error message. Your particular example would be written as:

```ocaml
(* requisition_util.ml *)
let validate_requisition { Requisition_t.start_date ; end_date } =
  match end_date with
  | None -> true
  | Some end_date ->
      Date.(end_date >= start_date)
      || failwith "end_date must be >= to start_date"
```

**Comment by brendanlong** [comment]
Ah cool, using `validator=` works for now, but the exception version would be more user-friendly if you feel like making that change :)

**Comment by shonfeder** [comment]
I'd be interested in helping with this, if no one is working on it!

I haven't looked at the code yet, but what if we did something like the following (to add additional "just works" functionality)?

1. If an exception is raised by the validation function, catch the message and use that (as @mjambon described).
2. If no error is raised, just supply the name of the validation function for message

Since this case fit (2), @brendanlong would have then seen something like

```
Validation error; expected "Requisition_util.validate_requisition"
```

**Comment by mjambon** [comment]
@shonfeder awesome! This sounds like a good plan. I think catching the standard `Failure` exception and letting the other exceptions alone is reasonable. Another option would be to require the user to raise a exception created for this special purpose, but I'm not sure how to make it really easy for the user.

Regarding (2), I'm not sure what's achievable. I'll let you find out.

In terms of code, `ov_emit.ml` is in charge of generating OCaml code, so you'll have to look at this. Runtime utility functions can be added under `atdgen-runtime/src/ov_...` as needed.

**Comment by rgrinberg** [comment]
In my opinion using `Failure` as the exception to signal errors isn't a good idea. This exception is already used as a kitchen sink in many other situations. I would hate to see it overloaded further. If we had to decide on an exception type, I think it would make sense to create a new exception in the runtime.

I'm also not entirely confident about overloading `validate` to have more than 1 way of signalling errors. I don't really see a good reason to add a validator that doesn't have a decent error message in the case of failure. But I suppose that since we value backwards compat, it will have to do for now.

**Comment by mjambon** [comment]
Instead of an exception, maybe we could just support an annotation field like `errmsg`:
```
<ocaml valid="..." valid.errmsg="">
```
It's a little verbose. An advantage I guess is that the same validation function could be used in different places with different error messages reflecting the atd context.

**Comment by rgrinberg** [comment]
How would make it work for error messages that depend on the concrete values being validated? For example, if we're validating a record we might want to include the field value that failed the validation.

**Comment by mjambon** [comment]
I was thinking the user-specified error message would be appended to the
automatically-generated error message, which shows a path made up of field
names.

Showing the value of the field without work from the user may be trickier.
I don't have ideas on this. For json parsing, we show the next few bytes of
input and it's generally helpful. Validators however are independent from
json parsing, so I don't know.

**Comment by shonfeder** [comment]
Sorry for the long delay here! I've had a frantic couple of weeks. I'll be able to dig in to this starting tonight, however.

**Comment by mjambon** [comment]
Any luck with this @shonfeder ? Don't hesitate to ask questions and comment on your experience here!

**Comment by mjambon** [comment]
@shonfeder Answering the easy questions now; will answer the rest later.

3: at some point I wanted to revamp the whole command line interface and didn't do it. Breaking compatibility is problematic, so if we do anything we should at least support the old interface. More realistically, the best compromise is to do what you suggest. The relevant issue is https://github.com/mjambon/atd/issues/105 and https://github.com/mjambon/atd/issues/93 is related.

4: please open an issue. We'd have to define how much of the work is done for the user and whether it fits in a the current atdgen package or if we have to create a new one because it adds dependencies (currently, the atd repo produces 4 opam packages; we can add more, if justified).

**Comment by mjambon** [comment]
@shonfeder 

1:
> For each root level type, it would be nice to have a function t -> Validation.error option. Is this already provided some how? If not, I can work on adding one.

I haven't looked into this issue, just copy-pasted into https://github.com/mjambon/atd/issues/134

2:
> For each root level type, it would be nice to have a function t -> Validation.error option. Is this already provided some how? If not, I can work on adding one.

Moved to https://github.com/mjambon/atd/issues/135

**Comment by mjambon** [comment]
We now have better error messages that include the name or code of the validator as found in `<ocaml valid="...">` thanks to @shonfeder (https://github.com/mjambon/atd/pull/132).

I'm hoping it's good enough and I'm closing the issue.
